name: current_build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  page_build:
    release:
      types:
        - created
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run test suite
      run:  vendor/bin/simple-phpunit